### PR TITLE
serve tiles from osm instead

### PR DESCRIPTION
**Pull request by graphaelli**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@graphaelli thanks this works perfectly. Can you make the same change in `jupyter-leaflet.js`?

**Comment by SylvainCorlay** [comment]
(the js side know the default values for all the attributes for the standalone case...)

**Comment by SylvainCorlay** [comment]
nevermind, merging and iterating.

**Comment by SylvainCorlay** [comment]
Release 0.2.1 with this. Conda-forge version coming soon.

**Comment by graphaelli** [comment]
wow that was fast, thanks @SylvainCorlay

**Comment by SylvainCorlay** [comment]
Yeah, the service interruption from mapquest was breaking the widgets example page http://jupyter.org/widgets.html

**Pull request merged**
