### PR TITLE
Add leaflet side-by-side support

### PR DESCRIPTION
**Pull request by jisantuc**
Overview
------

This PR adds leaflet side-by-side support to `jupyter-leaflet.js` and to leaflet.py.
An example notebook is included to demonstrate functionality.

Testing
------

- Run `Side-by-side.ipynb`
- :tada:

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@jisantuc I am really sorry this PR did not get attention before.

I am getting back into pushing ipyleaflet and am really excited about this feature.

This PR would need to be rebased upon master to be merged.

If you don't feel like rebasing your PR, I can close this and credit you for your commits in another PR.

**Comment by jisantuc** [comment]
I can take a look at rebasing this -- I tried a while ago but didn't have points available in the sprint to work on it so dropped it at the first sign of difficulty, but I can give it another shot.

**Comment by jisantuc** [comment]
OH nevermind I didn't see #124 -- that's also fine!

**Comment by SylvainCorlay** [comment]
@jisantuc all the commits in #124 are credited to you, so you will be listed in the contributors.

This is a pretty cool extension to leaflet. I am really excited about this.

**Comment by SylvainCorlay** [comment]
Closing this to carry on the conversation in #124.

**Pull request closed without merging**
